Algoritmo "atividade 12"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/08/2020
Var
// Seção de Declarações das variáveis 
numero: inteiro
ant,scs:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Ache antecessor e o sucessor deste numero:")
 leia (numero)
 ant<-numero-1
 scs<-numero+1
 // resultado
 escreval("Antecessor:",ant)
 escreval("Sucessor:",scs)

Fimalgoritmo