Algoritmo "atividade 2"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2020
Var
// Seção de Declarações das variáveis 
base,altura: inteiro
area: real


Inicio
// Seção de Comandos, procedimento, funções, operadores,
 escreval (" área de um triângulo ")
  leia (base,altura)
  area <-base*altura
  area<-area/2
   escreval (area)
   
fimalgoritmo