Algoritmo "atividade 6 "
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/08/2020
Var
// Seção de Declarações das variáveis 
celsius: real
fare: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite a temperatura em Fº:")
    leia(fare)
    celsius<- fare-32
    celsius <-celsius*5/9
     escreval ("A temperatura em Cº é:",celsius)

Fimalgoritmo