Algoritmo "atividade 11"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/08/2020
Var
// Seção de Declarações das variáveis 
impressoes:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  escreval("Mutiplos positivos de 7 inferiores a 1000")
  para impressoes de  7 ate <= 1000  passo 7 faca
 se (impressoes%1)=0 entao
 escreval (impressoes)
 fimse
 fimpara
 

Fimalgoritmo