Algoritmo "Atividade 3"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2020
Var
// Seção de Declarações das variáveis 
pnumero,snumero: inteiro
vc:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("Primeiro numero:")
leia (pnumero)
 escreval ("segunda numero:")
leia  (snumero)
 vc<-pnumero+snumero
  escreval("apresente o valor calculado=",vc)




Fimalgoritmo