Algoritmo "Atividade 5"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/08/2020
Var
// Seção de Declarações das variáveis 
celsius:inteiro
fare:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite a temperatura em cº:")
   leia (celsius)
   fare<- 9*celsius+160
   fare<-fare/5
   escreval ("A temperatura em fº é: ",fare)
   


Fimalgoritmo