Algoritmo "dois"
Var
// Seção de Declarações das variáveis 
 numero:vetor[1..2]de inteiro
 maior,menor,contador:inteiro
 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Informe o 1ºnumero:")
leia(numero[1])
menor<-numero[1]
para contador de 1 ate 2 faca
escreva("Informe o 2º numero:")
 leia(numero[contador])
se numero[contador]>maior entao
  maior<-numero[contador]
 fimse
 escreval("O Numero maior é:",maior)
 escreval ("O Numero menor é:",menor)

Fimalgoritmo