Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/08/2020
Var
// Seção de Declarações das variáveis 
a,b,c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Digite um numero inteiro")
 leia (a)
 b<- a-1
 c <- a+1
 escreval ("numero antecessor:",b "numero sucessor",c:)

Fimalgoritmo